package br.com.nebulatv.service;

import br.com.nebulatv.dao.Database;
import br.com.nebulatv.model.Title;
import java.sql.*;
import java.util.*;

public final class TitleService {
    public List<Title> all(){return query("SELECT id,external_id,name,overview,poster,backdrop,type,genres,year,rating,source,stream_url,runtime FROM titles ORDER BY id DESC",null);}
    public List<Title> allByType(String type){return query("SELECT id,external_id,name,overview,poster,backdrop,type,genres,year,rating,source,stream_url,runtime FROM titles WHERE type=? ORDER BY id DESC",new String[]{type});}
    public List<Title> recent(int limit){return query("SELECT id,external_id,name,overview,poster,backdrop,type,genres,year,rating,source,stream_url,runtime FROM titles ORDER BY id DESC LIMIT "+Math.max(1,limit),null);}
    public List<Title> search(String q){return query("SELECT id,external_id,name,overview,poster,backdrop,type,genres,year,rating,source,stream_url,runtime FROM titles WHERE lower(name) LIKE lower(?) OR lower(overview) LIKE lower(?) ORDER BY name LIMIT 80",new String[]{"%"+q+"%","%"+q+"%"});}
    public Title upsert(Title t){
        String sql="INSERT INTO titles(external_id,name,overview,poster,backdrop,type,genres,year,rating,source,stream_url,runtime) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source,external_id,name) DO UPDATE SET overview=excluded.overview,poster=excluded.poster,backdrop=excluded.backdrop,type=excluded.type,genres=excluded.genres,year=excluded.year,rating=excluded.rating,stream_url=excluded.stream_url,runtime=excluded.runtime";
        try(PreparedStatement p=Database.conn().prepareStatement(sql)){p.setString(1,t.externalId);p.setString(2,t.name);p.setString(3,t.overview);p.setString(4,t.poster);p.setString(5,t.backdrop);p.setString(6,t.type);p.setString(7,t.genres);p.setString(8,t.year);p.setString(9,t.rating);p.setString(10,t.source);p.setString(11,t.streamUrl);p.setInt(12,t.runtime);p.executeUpdate();}catch(Exception e){throw new RuntimeException(e);}Title x=findByKey(t.source,t.externalId,t.name);if(x!=null)t.id=x.id;return t;
    }
    private Title findByKey(String source,String externalId,String name){List<Title>a=query("SELECT id,external_id,name,overview,poster,backdrop,type,genres,year,rating,source,stream_url,runtime FROM titles WHERE source=? AND external_id=? AND name=? LIMIT 1",new String[]{source,externalId,name});return a.isEmpty()?null:a.get(0);}
    public Title find(long id){List<Title>a=query("SELECT id,external_id,name,overview,poster,backdrop,type,genres,year,rating,source,stream_url,runtime FROM titles WHERE id=?",new String[]{String.valueOf(id)});return a.isEmpty()?null:a.get(0);}
    public void delete(long id){try(PreparedStatement p=Database.conn().prepareStatement("DELETE FROM titles WHERE id=?")){p.setLong(1,id);p.executeUpdate();}catch(Exception e){throw new RuntimeException(e);}}
    public List<Title> favorites(long profileId){return query("SELECT t.id,t.external_id,t.name,t.overview,t.poster,t.backdrop,t.type,t.genres,t.year,t.rating,t.source,t.stream_url,t.runtime FROM titles t JOIN favorites f ON f.title_id=t.id WHERE f.profile_id=? ORDER BY t.name",new String[]{String.valueOf(profileId)});}
    public List<Title> progress(long profileId,boolean completed){return query("SELECT t.id,t.external_id,t.name,t.overview,t.poster,t.backdrop,t.type,t.genres,t.year,t.rating,t.source,t.stream_url,t.runtime,p.seconds,p.duration,p.completed FROM titles t JOIN progress p ON p.title_id=t.id WHERE p.profile_id=? AND p.completed=? ORDER BY p.last_played DESC",new String[]{String.valueOf(profileId),completed?"1":"0"});}
    public boolean isFavorite(long profileId,long titleId){try(PreparedStatement p=Database.conn().prepareStatement("SELECT 1 FROM favorites WHERE profile_id=? AND title_id=?")){p.setLong(1,profileId);p.setLong(2,titleId);try(ResultSet r=p.executeQuery()){return r.next();}}catch(Exception e){throw new RuntimeException(e);}}
    public boolean isWatched(long profileId,long titleId){try(PreparedStatement p=Database.conn().prepareStatement("SELECT completed FROM progress WHERE profile_id=? AND title_id=?")){p.setLong(1,profileId);p.setLong(2,titleId);try(ResultSet r=p.executeQuery()){return r.next()&&r.getInt(1)==1;}}catch(Exception e){throw new RuntimeException(e);}}
    public void toggleFavorite(long profileId,long titleId){try(PreparedStatement c=Database.conn().prepareStatement("SELECT 1 FROM favorites WHERE profile_id=? AND title_id=?")){c.setLong(1,profileId);c.setLong(2,titleId);try(ResultSet r=c.executeQuery()){if(r.next()){try(PreparedStatement d=Database.conn().prepareStatement("DELETE FROM favorites WHERE profile_id=? AND title_id=?")){d.setLong(1,profileId);d.setLong(2,titleId);d.executeUpdate();}}else{try(PreparedStatement i=Database.conn().prepareStatement("INSERT INTO favorites(profile_id,title_id) VALUES(?,?)")){i.setLong(1,profileId);i.setLong(2,titleId);i.executeUpdate();}}}}catch(Exception e){throw new RuntimeException(e);}}
    public void saveProgress(long profileId,long titleId,int seconds,int duration,boolean completed){try(PreparedStatement p=Database.conn().prepareStatement("INSERT INTO progress(profile_id,title_id,seconds,duration,completed,last_played) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(profile_id,title_id) DO UPDATE SET seconds=excluded.seconds,duration=excluded.duration,completed=excluded.completed,last_played=CURRENT_TIMESTAMP")){p.setLong(1,profileId);p.setLong(2,titleId);p.setInt(3,seconds);p.setInt(4,duration);p.setInt(5,completed?1:0);p.executeUpdate();}catch(Exception e){throw new RuntimeException(e);}}
    private List<Title> query(String sql,String[] args){List<Title>a=new ArrayList<>();try(PreparedStatement p=Database.conn().prepareStatement(sql)){if(args!=null)for(int i=0;i<args.length;i++)p.setString(i+1,args[i]);try(ResultSet r=p.executeQuery()){while(r.next()){Title t=new Title(r.getLong(1),r.getString(3),r.getString(7),r.getString(5),r.getString(6),r.getString(4),r.getString(8),r.getString(9),r.getString(10),r.getString(11));t.externalId=r.getString(2);t.streamUrl=r.getString(12);t.runtime=r.getInt(13);if(r.getMetaData().getColumnCount()>=16){t.progress=r.getInt(14);t.duration=r.getInt(15);t.watched=r.getInt(16)==1;}a.add(t);}}}catch(Exception e){throw new RuntimeException(e);}return a;}
}
